server:
  servlet:
    context-path: /admin
    use-forward-headers: true

spring:
  security:
    user:
      name: tim
      password: '{cipher}5930ce1dd8cff9d0fe9002ea488964786df68ecc021528ad6af46617da54c98c'
  boot:
    admin:
      monitor: 
        default-retries: 2
      ui:
        title: Gundmann Spring Boot Admin
      notify:
        mail:
          to: tim@gundmann.dk
          from: smtp@gundmann.dk
          
  mail:
    host: smtp.gmail.com
    port: 587
    user-name: smtp@gundmann.dk
    password: '{cipher}7173a4c253e033d72e975ea08dc4c62fd040123981d5f4fef411b1acc962dfc8'
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

logging.file=/var/log/spring-boot-application.log
logging:
  file:
    max-history: 10
    max-size: 100MB
  pattern:
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
