spring:
  security:
    user:
      name: tim
      password: '{cipher}5930ce1dd8cff9d0fe9002ea488964786df68ecc021528ad6af46617da54c98c'
  boot:
    admin:
      ui:
        title: Gundmann Spring Boot Admin
